name: app
type: nodejs:16
disk: 1024

relationships:
  database: "db:postgresql"
  queue: "queue:redis"

dependencies:
  nodejs:
    "npm": "*"

hooks:
  build: |
    npm install n8n -g

web:
  commands:
    start: |
      n8n start

workers:
  queue:
    size: S
    commands:
      start: |
        n8n worker

mounts:
  "/.n8n/config":
    source: local
    source_path: ".n8n/config" 

  "/.cache":
    source: local
    source_path: "cache"
