name: main
type: nodejs:16
disk: 1024

relationships:
  database: "db:postgresql"
  queue: "queue:redis"

dependencies:
  nodejs:
    "npm": "*"

hooks:
  build: |
    set -e
    if [ -e $PLATFORM_CACHE_DIR/n8n-key.txt ]; then
      export N8N_ENCRYPTION_KEY=$(cat $PLATFORM_CACHE_DIR/n8n-key.txt)
    else
      echo $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 30) > $PLATFORM_CACHE_DIR/n8n-key.txt
      export N8N_ENCRYPTION_KEY=$(cat $PLATFORM_CACHE_DIR/n8n-key.txt)
    fi;
    cp $PLATFORM_CACHE_DIR/n8n-key.txt $PLATFORM_APP_DIR/n8n-key.txt
    npm install n8n -g

web:
  commands:
    start: |
      export N8N_ENCRYPTION_KEY=$(cat $PLATFORM_APP_DIR/n8n-key.txt)
      n8n start

workers:
  queue1:
    size: S
    commands:
      start: |
        export N8N_ENCRYPTION_KEY=$(cat $PLATFORM_APP_DIR/n8n-key.txt)
        n8n worker
  queue2:
    size: S
    commands:
      start: |
        export N8N_ENCRYPTION_KEY=$(cat $PLATFORM_APP_DIR/n8n-key.txt)
        n8n worker

mounts:
  "/.n8n":
    source: local
    source_path: "n8n" 

  "/.cache":
    source: local
    source_path: "cache"

variables:
  env:
    "NODE_OPTIONS": "--max-old-space-size=2048"
