name: webhook
type: nodejs:16
disk: 768

relationships:
  database: "db:postgresql"
  queue: "queue:redis"

dependencies:
  nodejs:
    "npm": "*"

hooks:
  build: !include
    type: string
    path: ops/hooks/build.sh
  deploy: !include
    type: string
    path: ops/hooks/deploy.sh
  post_deploy: !include
    type: string
    path: ops/hooks/post_deploy.sh

web:
  commands:
    start: !include
      type: string
      path: ops/start.sh

mounts:
  "/.n8n":
    source: local
    source_path: "n8n" 

  "/.cache":
    source: local
    source_path: "cache"

variables:
  env:
    "NODE_OPTIONS": "--max-old-space-size=512"

source:
  operations:
    auto-update:
      command: !include
        type: string
        path: ops/source/auto-update.sh

