"https://{default}":
  type: upstream
  upstream: "main:http"
  id: "main"

"https://hook.{default}":
  type: upstream
  upstream: "webhook:http"
  id: "webhook"

"https://{default}/files"
  type: upstream
  upstream: "main:http"
  cache:
    enabled: true

"https://www.{default}":
  type: redirect
  to: "https://{default}"
